### PR TITLE
Add section on community pipeline

### PR DESCRIPTION
**Pull request by jhamrick**
@willingc and I collaborated on this based on the discussion on community pipeline at the dev meeting.

### CODE REVIEW

**Comment by takluyver** [comment]
Cross linking the project overview map I made a start on:
https://github.com/jupyter/jupyter/pull/127

**Comment by willingc** [comment]
Thanks @takluyver.

**Comment by damianavila** [comment]
Should we link issues/pr with the effective implementation?

For instance, @takluyver started some work in the mapping stuff as it was linked above...

**Pull request merged**
