### PR TITLE
Include spark architectural recommendation section

### PR DESCRIPTION
**Pull request by rgbkrk**
/cc @lbustelo for review/expansion

### CODE REVIEW

**Comment by lbustelo** [comment]
@rgbkrk What are your thoughts RE: making sure that Notebook server has builtin support to provision remote kernels through use of the Kernel Gateway? @jtyberg put together [nb2kg](https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg) as a demo, but I think it is time to consider making this something that is available out-of-the-box in Jupyter and that can be configured using `kernel.json` and the likes.

**Comment by rgbkrk** [comment]
I don't personally (read: the infrastructure I currently support doesn't) have a need for remote kernels through the kernel gateway - we're treating our JupyterHub-like setup as a kernels endpoint (over the jupyter websockets) while working on the UI with both nteract and jupyter. ZeroMQ is not currently problematic for us between server <--> kernel. I'm certainly in favor of having a well specified `kernel.json` for websocket based kernels. @minrk is a better judge there.

**Comment by willingc** [comment]
Not related to PR but passing along a recent PySpark/Jupyter article: https://opendatascience.com/blog/installing-jupyter-with-the-pyspark-and-r-kernels-for-spark-development/

**Comment by minrk** [comment]
Adding websockets as an official transport for kernels from the server's perspective (i.e. REST+ws API alongside zmq) is an interesting proposition. I'm still not sure about it being in the default behavior, but it's definitely a good thing to continue to use / develop in the nb2kg extension.

**Pull request merged**
