### PR TITLE
Add UX survey items to notebook future

### PR DESCRIPTION
**Pull request by parente**
We discussed the results of the UX survey. I'm opening this PR to suggest that the roadmap should at least capture the top user requests for consideration in future development plans. I do not know who would do the implementation or how, but it feels disingenuous to leave it out completely.

I put the bullets under Notebook -> Future for now.

Strawman: Could version control, better text editing features (e.g., vi shortcuts), dev tools (e.g., variable watcher) be implemented as Jupyter Lab plugins to start to draw interest toward the new UX?

### CODE REVIEW

**Comment by sccolbert** [comment]
LGTM and :+1: for strawman lab plugins

**Comment by rgbkrk** [comment]
Definite :+1:

**Comment by damianavila** [comment]
> Strawman: Could version control, better text editing features (e.g., vi shortcuts), dev tools (e.g., variable watcher) be implemented as Jupyter Lab plugins to start to draw interest toward the new UX?

Nice idea...

**Comment by Carreau** [comment]
+1

**Comment by rgbkrk** [comment]
These are all goals I'd like us to go after (as I've already voted). With no amount of detraction and only positive responses, I think this is safe to merge.

**Comment by sccolbert** [comment]
:shipit:

**Pull request merged**
