### PR TITLE
Add heading stub for Qt Console

### PR DESCRIPTION
**Pull request by afshin**
The roadmap thinking for the new version of the console that will appear in JupyterLab needs to be documented, but others will need to chime in.

This PR is just to raise the subject.

### CODE REVIEW

**Comment by minrk** [comment]
Great! What are the first high-level milestones for this project?

**Comment by afshin** [comment]
@minrk As I understand it, the primary milestone is for the web-based console inside JupyterLab to achieve feature parity with the Qt Console application.

FYI, since you know the Qt Console well, you might be interested in following along the development of the web version, which is happening in this PR: https://github.com/jupyter/jupyter-js-notebook/pull/208

**Comment by fperez** [comment]
Thanks @afshin! I would add some basic notes about feature parity, availability as a standalone tool (wrapped in a simple qt container or other JS wrapper?), expected support for widgets (or not - they don't work in today's qt console, but they might in a new JLab based one), and any expected feature regressions, if any.

**Comment by afshin** [comment]
Thanks for the guidance @fperez, I've updated the conversation.

**Comment by blink1073** [comment]
Thanks @afshin, this looks good to me.

**Pull request merged**
