### PR TITLE
Add ipywidgets roadmap

### PR DESCRIPTION
**Pull request by jdfreder**
From our meeting today,

@fperez @ellisonbg @sylvaincorlay @lbustelo

### CODE REVIEW

**Comment by ellisonbg** [comment]
Great I can look this over when you are at Cal Poly tomorrow.

**Comment by jdfreder** [comment]
Sweet, that sounds good.  I'm pretty sure it will need some tweaks after with talk with @sylvaincorlay

**Comment by SylvainCorlay** [comment]
Regarding widget styling.

## Top-level `DOMWidget` attributes

Regarding the styling of widget, I think that we all agreed that having all the following attributes at the top-level DOMWidget is bad:

`width`, `height`, `padding`, `margin`, `color`, `background_color`, `border_color`, `border_width`, `border_radius`, `border_style`, `font_style`, `font_weight`, `font_size`, `font_family`

Ideally, the top-level model for e.g. a slider should be reduced to the core slider model attributes. Besides, attributes names like `name`, `margin` are very common and should eventually be available to the user for other things that styling.
Hence, deprecating these in 5.0 is really a must.

## `_css` and `_dom_classes`

I think that letting the user access css from the python side is bad because it requires them to know the dom structure of each individual widget. The implications would be that we would need this dom structure
- to remain the same in future versions of ipywidgets for their custom css to continue working :-1:
  
  (We will break user code when we start using a different html widget toolkit)
- to be documented as part of the API of ipywidgets  :-1:
  
  (We cannot simply forward them to bootstrap's API since we are using a mixture of bootstrap, jquery-ui and custom DOM manipulation)
- finally, saying that the official API to style a widget is to ask the user to
  - look into the developer tools to find the right selector for a slider handle :-1: ,
  - use the `%%css` magic to enter something like `.slider-handle { color: #A00; }` :-1: 
  
  is really not ideal.

As a consequence, in the effort to reduce the API, since `_css` and `_dom_classes` are _not_ public API at the moment, I would be in favor of removing them completely for 5.0.

## Regarding the `Style` widget

The `Style` widget provides a replacement for the API that we deprecate in the `DOMWidget` model. It allows setting properties to the main element of a widget. In the current development version of ipywidgets, you can simply do

``` python
slider = IntSlider()
slider.style.width = '10px'
```

and we don't expose styling of the inner dom structure of the widget. This is mostly meant for people to be able to align things properly and control the general layout of their GUI, and basic color properties. 

I would be in favor of keeping this API around as a replacement for the one that we deprecate (top-level `DOMWidget` attributes).

## What if we _really_ want more flexibility without writing our custom widgets.

Let's say that we really have a lot of people asking for the specific ability to change the color or shape of the handle of a slider. Rather than exposing the DOM selector for the handle, we can do the following:
1. add an a `handle_style` attribute to the slider model, that should be an instance of `Style` widget.
   
   ``` Python
   class IntSlider(_Int):
       [...]
       handler_style = Instance(trait=Style(), sync=True, **widget_serialization)
   ```
2. Document that the API for changing the handle style is the following
   
   ``` Python
   slider = IntSlider()
   slider.handle_style.border_radius = '3px'
   ```

From the user's perspective, it is 
- pure Python :+1: . No knowledge of web development is required.

From our perspective
- we can easily change our js implementation of the slider and expose the same API to the user.

**Comment by SylvainCorlay** [comment]
We had another call with @jdfreder and @ellisonbg .
- We agreed to remove `_css` and `_dom_classes` traits, **but** we will add public `[add/remove]_class` methods. 
- We also will be deprecating the main `DOMWidget` styling attributes (width, height etc)
- We are keeping the `Style` widget, but will reduce the list of css attributes that its supports to what is currently supported in the DOMWidget model, and the flexbox-related attributes.

**Comment by ellisonbg** [comment]
Thanks for summarizing! I will let @jdfreder update the roadmap PR

On Thu, Dec 17, 2015 at 10:54 AM, Sylvain Corlay notifications@github.com
wrote:

> We had another call with @jdfreder https://github.com/jdfreder and
> @ellisonbg https://github.com/ellisonbg .
> - We agreed to remove _css and _dom_classes traits, _but_ we will add
>   public [add/remove]_class methods.
> - We also will be deprecating the main DOMWidget styling attributes
>   (width, height etc)
> - We are keeping the Style widget, but will reduce the list of css
>   attributes that its supports to what is currently supported in the
>   DOMWidget model, and the flexbox-related attributes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/roadmap/pull/3#issuecomment-165546893.

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Rebased and updated

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
